data:
  data_path: 'health_folder\mental_heath_unbanlanced.csv'
  test_size: 0.4
  random_state: 42
  test_evaluation_size: 0.2

preprocessing_data:
  train_path: 'data/raw/train.csv'
  test_path: 'data/raw/test.csv'

training_data:
  train_data: 'data\preprocessed_data\train_prepocessed.csv'

testing_data:
  test_data: 'data\preprocessed_data\test_preprocessed.csv'

validation_data:
  eval_data: 'data/preprocessed_data/eval_preprocessed.csv'

vectorizer:
  max_features: 500
  ngram_range: [1, 2]
  max_df: 0.7 

logistic:
  solver: 'lbfgs'
  max_iter: 500
  C: 1

saved_model:
  model: 'pickle/log_model.pkl'

vectorizer_model:
  vec: 'pickle/vectorizer.pkl'