stages:
  data_ingestion:
   cmd: python src/data_modelling/data_ingestion.py
   deps: 
     - src/data_modelling/data_ingestion.py
     - config.yaml
  
  data_preprocessing:
   cmd: python src/data_modelling/data_preprocess.py
   deps:
     - src/data_modelling/data_preprocess.py
     - config.yaml
  model_building:
   cmd: python src/mod/model_building.py
   deps:
    - src/mod/model_building.py
    - config.yaml

  evaluation:
   cmd: python src/mod/model_evaluation.py
   deps:
    - src/mod/model_evaluation.py
    - config.yaml